### ISSUE TITLE
ethz数据集和citypersons数据集问题

### ISSUE THREAD

**Issue by shiwufuya** [RainBowLuoCS/DiffusionTrack#13]
Traceback (most recent call last):
  File "D:\python document\DiffusionTrack-main\tools\convert_ethz_to_coco.py", line 25, in <module>
    img_paths, label_paths = load_paths(DATA_FILE_PATH)
  File "D:\python document\DiffusionTrack-main\tools\convert_ethz_to_coco.py", line 12, in load_paths
    with open(data_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data_path/eth.train'

Traceback (most recent call last):
  File "D:\python document\DiffusionTrack-main\tools\convert_cityperson_to_coco.py", line 24, in <module>
    img_paths, label_paths = load_paths(DATA_FILE_PATH)
  File "D:\python document\DiffusionTrack-main\tools\convert_cityperson_to_coco.py", line 11, in load_paths
    with open(data_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data_path/citypersons.train'

**Comment by RainBowLuoCS** [comment]
看看bytetrack 里面有
